
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SentenciaModulo = 29;
  public static final int End = 17;
  public static final int Double = 9;
  public static final int corcheteE = 15;
  public static final int corcheteC = 16;
  public static final int OPMultDiv = 19;
  public static final int Sub = 28;
  public static final int coma = 47;
  public static final int Comentario = 22;
  public static final int Else = 25;
  public static final int OperadorRelacional = 10;
  public static final int struct = 43;
  public static final int OR = 35;
  public static final int Punto = 12;
  public static final int Return = 40;
  public static final int Console = 44;
  public static final int While = 33;
  public static final int ReadLine = 50;
  public static final int IF = 32;
  public static final int Cadena = 4;
  public static final int then = 38;
  public static final int For = 31;
  public static final int EOF = 0;
  public static final int ContinuacionLinea = 21;
  public static final int RMain = 53;
  public static final int Function = 39;
  public static final int And = 36;
  public static final int error = 1;
  public static final int WriteLine = 46;
  public static final int Op_Booleano = 27;
  public static final int Integer = 8;
  public static final int Do = 34;
  public static final int ERROR = 24;
  public static final int llaveE = 13;
  public static final int llaveC = 14;
  public static final int Enter = 20;
  public static final int OPRestSuma = 18;
  public static final int Dim = 41;
  public static final int New = 52;
  public static final int String = 48;
  public static final int TO = 45;
  public static final int concatenacion = 37;
  public static final int Identificador = 2;
  public static final int parentesisE = 6;
  public static final int parentesisC = 7;
  public static final int espacio = 54;
  public static final int Boolean = 11;
  public static final int AS = 42;
  public static final int Declaracion = 30;
  public static final int Numero = 3;
  public static final int Loop = 51;
  public static final int Next = 49;
  public static final int Main = 26;
  public static final int Igual = 23;
  public static final int Comilla = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Identificador",
  "Numero",
  "Cadena",
  "Comilla",
  "parentesisE",
  "parentesisC",
  "Integer",
  "Double",
  "OperadorRelacional",
  "Boolean",
  "Punto",
  "llaveE",
  "llaveC",
  "corcheteE",
  "corcheteC",
  "End",
  "OPRestSuma",
  "OPMultDiv",
  "Enter",
  "ContinuacionLinea",
  "Comentario",
  "Igual",
  "ERROR",
  "Else",
  "Main",
  "Op_Booleano",
  "Sub",
  "SentenciaModulo",
  "Declaracion",
  "For",
  "IF",
  "While",
  "Do",
  "OR",
  "And",
  "concatenacion",
  "then",
  "Function",
  "Return",
  "Dim",
  "AS",
  "struct",
  "Console",
  "TO",
  "WriteLine",
  "coma",
  "String",
  "Next",
  "ReadLine",
  "Loop",
  "New",
  "RMain",
  "espacio"
  };
}

